require('dotenv').config();
const express=require('express'),cors=require('cors'),crypto=require('crypto'),path=require('path'),bcrypt=require('bcryptjs');
const {createClient}=require('@supabase/supabase-js');
const app=express(), publicDb=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_ANON_KEY), db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY);
const statuses=['Menunggu','Diproses','Selesai'];
const bad=(res,message,status=400)=>res.status(status).json({error:message});
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const validUrl=value=>{try{return /^https?:$/.test(new URL(value).protocol)}catch{return false}};
async function requireAdmin(req,res,next){const token=(req.headers.authorization||'').replace(/^Bearer\s+/,'');if(!token)return bad(res,'Belum login',401);const {data,error}=await publicDb.auth.getUser(token);if(error||!data.user)return bad(res,'Token admin tidak valid',401);const {data:profile,error:profileError}=await db.from('profiles').select('*').eq('id',data.user.id).single();if(profileError||!profile||!['super_admin','admin_bidang','pic_staff'].includes(profile.role))return bad(res,'Akses admin ditolak',403);req.admin={...profile,auth_id:data.user.id};next()}
async function addLog(requestId,actorId,action,oldValue,newValue){const {error}=await db.from('activity_logs').insert({request_id:requestId,actor_id:actorId,action,old_value:oldValue==null?null:String(oldValue),new_value:newValue==null?null:String(newValue)});if(error)throw error}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function assignPic(requestId){for(let attempt=0;attempt<3;attempt++){const {data,error}=await db.rpc('assign_random_pic',{request_id:requestId});if(!error)return data;const transient=/fetch failed|timeout|ECONNRESET|ECONNREFUSED|connect/i.test(`${error.message||''} ${error.details||''}`);if(!transient||attempt===2){if(transient)throw new Error('Supabase tidak dapat dihubungi saat menentukan PIC. Periksa koneksi internet lalu coba lagi.');throw error}await wait(500*(attempt+1))}}
async function requestRows(query){const {data,error}=await query.order('created_at',{ascending:false});if(error)throw error;return (data||[]).map(r=>({...r,assigned_to:r.assigned_to||null}))}
async function purgeExpiredArchives(){const cutoff=new Date(Date.now()-30*24*60*60*1000).toISOString();const {error}=await db.from('requests').delete().not('archived_at','is',null).lt('archived_at',cutoff);if(error)throw error}
app.use(cors(),express.json(),express.static(path.join(__dirname,'frontend','dist')));
purgeExpiredArchives().catch(error=>console.error('Gagal membersihkan arsip kadaluarsa:',error));
setInterval(() => purgeExpiredArchives().catch(error=>console.error('Gagal membersihkan arsip kadaluarsa:',error)), 24*60*60*1000);
app.get('/api/public/meta',wrap(async(req,res)=>{const {data,error}=await db.from('divisions').select('id,name,password_enabled').order('name');if(error){if(error.code==='42703'||/password_enabled/i.test(error.message||''))return bad(res,'Kolom divisions.password_enabled belum tersedia. Jalankan migration password bidang di Supabase SQL Editor.',500);throw error}res.json({divisions:data||[]})}));
app.post('/api/public/divisions/:id/access',wrap(async(req,res)=>{const password=String(req.body?.password||'');const {data,error}=await db.from('divisions').select('id,name,password_hash,password_enabled').eq('id',req.params.id).maybeSingle();if(error){if(error.code==='42703'||/password_(hash|enabled)/i.test(error.message||''))return bad(res,'Kolom pengaturan password bidang belum tersedia. Jalankan migration 20260930_add_division_passwords.sql di Supabase SQL Editor.',500);throw error}if(!data)return bad(res,'Bidang tidak ditemukan',404);if(!data.password_enabled)return res.json({ok:true,division:{id:data.id,name:data.name}});if(!password)return bad(res,'Password bidang wajib diisi',400);if(!data.password_hash)return bad(res,'Password bidang belum disetel. Minta admin menjalankan seed atau mengganti password bidang.',503);if(!(await bcrypt.compare(password,data.password_hash)))return bad(res,'Password bidang salah',401);res.json({ok:true,division:{id:data.id,name:data.name}})}));
app.post('/api/public/requests',wrap(async(req,res)=>{const b=req.body||{};if(!b.requester_name||!b.division||!b.title||!['Feed','Story','Reels'].includes(b.post_type)||!Number.isInteger(+b.slide_count)||+b.slide_count<1||!validUrl(b.draft_url)||!b.deadline)return bad(res,'Lengkapi data request dengan benar');const token=crypto.randomBytes(24).toString('hex');const {data,error}=await db.from('requests').insert({public_token:token,requester_name:String(b.requester_name).trim(),division:String(b.division).trim(),title:String(b.title).trim(),post_type:b.post_type,slide_count:+b.slide_count,draft_url:b.draft_url,deadline:b.deadline,description:b.description||null}).select('id,public_token').single();if(error)throw error;const assigned=await assignPic(data.id);await addLog(data.id,null,'Request dibuat',null,'Menunggu');res.status(201).json({...data,assigned_to:assigned?.[0]?.assigned_to||assigned?.assigned_to||null})}));
app.get('/api/public/requests',wrap(async(req,res)=>{const token=String(req.query.token||''),division=String(req.query.division||'').trim();if(!/^[a-f0-9]{48}$/.test(token))return bad(res,'Token request tidak valid',401);await purgeExpiredArchives();let query=db.from('requests').select('id,requester_name,division,title,post_type,slide_count,draft_url,deadline,description,status,assigned_to,admin_note,result_url,created_at,updated_at,archived_at').eq('public_token',token);if(division)query=query.eq('division',division);const rows=await requestRows(query);res.json(rows)}));
app.post('/api/auth/login',wrap(async(req,res)=>{let {email,password}=req.body||{};if(String(email).toLowerCase()==='admin')email='admin@kmi.id';const {data,error}=await publicDb.auth.signInWithPassword({email,password});if(error)return bad(res,'Username atau password salah',401);const {data:profile,error:profileError}=await db.from('profiles').select('*').eq('id',data.user.id).single();if(profileError||!profile||!['super_admin','admin_bidang','pic_staff'].includes(profile.role))return bad(res,'Akun bukan admin',403);res.json({token:data.session.access_token,user:profile})}));
app.get('/api/admin/stats',requireAdmin,wrap(async(req,res)=>{let query=db.from('requests').select('status').is('archived_at',null);if(req.admin.role==='admin_bidang')query=query.eq('division',req.admin.division);const {data,error}=await query;if(error)throw error;const summary={total:data?.length||0};for(const status of statuses)summary[status]=(data||[]).filter(row=>row.status===status).length;res.json(summary)}));
app.get('/api/admin/divisions',requireAdmin,wrap(async(req,res)=>{const {data,error}=await db.from('divisions').select('id,name,description,password_enabled').order('name');if(error){if(error.code==='42703'||/password_enabled/i.test(error.message||''))return bad(res,'Kolom divisions.password_enabled belum tersedia. Jalankan migration password bidang di Supabase SQL Editor.',500);throw error}res.json({data:data||[]})}));
app.patch('/api/admin/divisions/:id/password',requireAdmin,wrap(async(req,res)=>{const password=String(req.body?.password||'');if(password.length<6)return bad(res,'Password bidang minimal 6 karakter');const hash=await bcrypt.hash(password,12);const {data,error}=await db.from('divisions').update({password_hash:hash}).eq('id',req.params.id).select('id,name').single();if(error||!data)return bad(res,'Bidang tidak ditemukan',404);res.json({ok:true,division:data})}));
app.patch('/api/admin/divisions/:id/password-mode',requireAdmin,wrap(async(req,res)=>{if(typeof req.body?.enabled!=='boolean')return bad(res,'Status password tidak valid');const {data,error}=await db.from('divisions').update({password_enabled:req.body.enabled}).eq('id',req.params.id).select('id,name,password_enabled').single();if(error){if(error.code==='42703'||/password_enabled/i.test(error.message||''))return bad(res,'Kolom password_enabled belum tersedia. Jalankan migration 20260930_add_division_passwords.sql di Supabase SQL Editor.',500);throw error}if(!data)return bad(res,'Bidang tidak ditemukan',404);res.json({ok:true,division:data})}));
app.get('/api/admin/requests',requireAdmin,wrap(async(req,res)=>{let query=db.from('requests').select('id,requester_name,division,title,post_type,slide_count,draft_url,deadline,description,status,assigned_to,admin_note,result_url,created_at,updated_at,archived_at');query=req.query.archived==='true'?query.not('archived_at','is',null):query.is('archived_at',null);if(req.admin.role==='admin_bidang')query=query.eq('division',req.admin.division);if(req.query.status)query=query.eq('status',req.query.status);const data=await requestRows(query);res.json({data:data.slice(0,100),total:data.length})}));
app.post('/api/admin/requests/:id/assign-random',requireAdmin,wrap(async(req,res)=>{const {data:current,error:readError}=await db.from('requests').select('id,division,assigned_to').eq('id',req.params.id).single();if(readError||!current)return bad(res,'Request tidak ditemukan',404);if(req.admin.role==='admin_bidang'&&current.division!==req.admin.division)return bad(res,'Request bukan bidang Anda',403);const data=await assignPic(current.id);const assigned=data?.[0]||data;if(!assigned)return bad(res,'PIC tidak berhasil ditentukan',500);await addLog(current.id,req.admin.auth_id,'PIC',current.assigned_to,assigned.assigned_to);res.json(assigned)}));
app.patch('/api/admin/requests/:id',requireAdmin,wrap(async(req,res)=>{const b=req.body||{};if(b.status&&!statuses.includes(b.status))return bad(res,'Status tidak valid');if(b.result_url&&!validUrl(b.result_url))return bad(res,'Link hasil harus URL valid');const {data:current,error:readError}=await db.from('requests').select('*').eq('id',req.params.id).single();if(readError||!current)return bad(res,'Request tidak ditemukan',404);if(req.admin.role==='admin_bidang'&&current.division!==req.admin.division)return bad(res,'Request bukan bidang Anda',403);const update={};for(const key of ['status','assigned_to','admin_note','result_url'])if(b[key]!==undefined)update[key]=b[key]||null;update.updated_at=new Date().toISOString();if(update.status==='Selesai'){update.completed_at=current.completed_at||new Date().toISOString();update.archived_at=current.archived_at||new Date().toISOString()}const {data,error}=await db.from('requests').update(update).eq('id',current.id).select().single();if(error)throw error;for(const key of ['status','assigned_to','admin_note','result_url','archived_at'])if(update[key]!==undefined&&String(update[key]||'')!==String(current[key]||''))await addLog(current.id,req.admin.auth_id,key,current[key],update[key]);res.json(data)}));
app.post('/api/admin/requests/:id/archive',requireAdmin,wrap(async(req,res)=>{const {data:current,error:readError}=await db.from('requests').select('id,status,division').eq('id',req.params.id).single();if(readError||!current)return bad(res,'Request tidak ditemukan',404);if(current.status!=='Selesai')return bad(res,'Hanya request Selesai yang dapat diarsipkan');if(req.admin.role==='admin_bidang'&&current.division!==req.admin.division)return bad(res,'Request bukan bidang Anda',403);const {error}=await db.from('requests').update({archived_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',current.id);if(error)throw error;await addLog(current.id,req.admin.auth_id,'Request diarsipkan',null,'Selesai');res.json({ok:true})}));
app.delete('/api/admin/requests/:id',requireAdmin,wrap(async(req,res)=>{const {data:current,error:readError}=await db.from('requests').select('id,status,division').eq('id',req.params.id).single();if(readError||!current)return bad(res,'Request tidak ditemukan',404);if(current.status!=='Selesai')return bad(res,'Hanya request Selesai yang dapat dihapus');if(req.admin.role==='admin_bidang'&&current.division!==req.admin.division)return bad(res,'Request bukan bidang Anda',403);const {error}=await db.from('requests').delete().eq('id',current.id);if(error)throw error;res.json({ok:true})}));
app.use((error,req,res,next)=>{console.error(error);bad(res,error.message||'Terjadi kesalahan server',500)});
if(!process.env.SUPABASE_URL||!process.env.SUPABASE_ANON_KEY||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw new Error('SUPABASE_URL, SUPABASE_ANON_KEY, dan SUPABASE_SERVICE_ROLE_KEY wajib diisi');
if(require.main===module){const port=process.env.PORT||4001;app.listen(port,'0.0.0.0',()=>console.log(`API berjalan di port ${port}`))}
module.exports=app;
